services:

  app:
    build: .
    container_name: medsoft-app
    ports:
      - "8080:8080"
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: medsoft-ngrok
    environment:
      - NGROK_AUTHTOKEN=3B50567z3bl66vuerI7sfsyYHjc_85HtENNBxsCZqHYECnsqY
    command: http app:8080
    ports:
      - "4040:4040"
    depends_on:
      - app
    restart: unless-stopped